title: Trackerboy
description: >-
  Cross platform Game Boy / Game Boy Color music tracker
baseurl: ""
url: "https://www.trackerboy.org"

sass:
  style: compressed

repourl: https://github.com/stoneface86/trackerboy

socials:
  github: 'stoneface86'
  twitter: 'stoneface86'

nav:
  - link: '/'
    name: 'Home'
  - link: '/downloads/'
    name: 'Downloads'
  - link: '/changes/'
    name: 'Changes'
  - link: '/manual/'
    name: 'User Manual'
  - link: 'https://github.com/stoneface86/trackerboy/issues/10'
    name: 'Roadmap'
  - link: 'https://github.com/stoneface86/trackerboy'
    name: 'GitHub'
  - link: 'https://github.com/stoneface86/trackerboy/issues/'
    name: 'Bug Tracker'

collections:
  downloads:
    output: true
    permalink: /:collection/:path/
    sort_by: date

github: [metadata]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - ci.py
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

